# Configure a default setup of Home Assistant (frontend, api, etc)
#teste
default_config:

http:
#  base_url: http://smartboardneww.duckdns.org/
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


mqtt:
   client_id: hassio
   username: smartboard
   password: smartboard.123
   broker: smartboardneww.duckdns.org
   #port: 1883
   port: 8883
   certificate: auto
   
   ##tentattivas
   #certificate: /ssl/certificate.crt
   #certificate: /ssl/cert.crt

   ##Referencia:
   # certificate: /ssl/chain.pem
   # client_key: /ssl/b5dd525b0f-certificate.pem.crt
   # client_cert: /ssl/b5dd525b0f-private.pem.key
   
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include light.yaml
